yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Группа',
                             max_length=200,
                             help_text='Добавьте название группы')
    slug = models.SlugField('Слаг', unique=True, help_text='Добавьте слаг')
    description = models.TextField('Описание', help_text='Добавьте описание')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class Post(models.Model):
    text = models.TextField('Текст поста',
                            blank=False,
                            help_text='Введите тест поста')
    pub_date = models.DateTimeField('Дата публикации',
                                    auto_now_add=True,
                                    help_text='Добавьте дату публикации')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Впишите имя автора поста')

    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу')

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

yatube/posts/forms.py
from django import forms
from django.forms import ModelForm

from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        widgets = {
            'text': forms.Textarea(attrs={'rows': 10, 'cols': 40}),
        }
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from yatube import settings

from .forms import PostForm
from .models import Group, Post, User


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.PAGE_SIZE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, settings.PAGE_SIZE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    post_list = user.posts.all()
    paginator = Paginator(post_list, settings.PAGE_SIZE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    post_number = post_list.count()
    context = {
        'page_obj': page_obj,
        'post_number': post_number,
        'author': user,  # здесь мне нужен этот контекст,
        # не могу к нему обратиться из шаблона
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    user = get_object_or_404(User, username=post.author)
    post_number = user.posts.filter(author=user).count()
    context = {
        'post': post,
        'post_number': post_number,
        'post_id': post_id,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):

    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author)

    return render(request, 'posts/create_post.html',
                  {'form': form, 'username': request.user})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        raise Http404

    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:post_detail', post_id=post_id)

    return render(request, 'posts/create_post.html',
                  {'form': form, 'username': request.user, 'is_edit': True})

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}Новый пост{% endblock %}
{% block header %}Новый пост{% endblock %}
{% block content %}
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-body">
              <div class="card-header">
                {% if is_edit %}
                  Редактировать запись
                {% else %}
                  Добавить запись
                {% endif %}
              </div>
              <form action="{% url 'posts:post_create' %}" method="post">
              {% csrf_token %}
                <div class="form-group row my-3 p-3">
                  <label for="id_text">Текст поста<span class="required text-danger" >*</span></label>
                  {{ form.text }}
                  <span class="helptext text-muted">Текст нового поста</span>
                </div>

                <div class="form-group row my-3 p-3">
                  <label for="id_group">Group</label>
                  {{ form.group }}
                  <span class="helptext text-muted">Группа, к которой будет относиться пост</span>
                </div>

              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества{% endblock %}
{% block content %}
  <div class="container" href="{% url 'posts:group_list' group.slug %}">
    <h1>{{ group.title }}</h1>
        <p>
          {{ group.description }}
        </p>
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>{{ post.text }}</p>
          <hr>
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
    <div class="container">
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>{{ post.text }}</p>
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %} Пост {{ post.text|truncatewords:30 }} {% endblock %}
{% block content %}
{% load user_filters %}
    <!-- Подключены иконки, стили и заполенены мета теги -->
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            <!-- если у поста есть группа -->
            {% if post.group %}
            Группа: {{ group.title }}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: <span>{{ post_number }}</span>
            </li>
            <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
           {{ post.text }}
          </p>
          {% if user == post.author %}
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
              редактировать запись
            </a>
          {% endif %}
        </article>
      </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}
{% block content %}
{% load user_filters %}
      <div class="container py-5">
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ post_number }} </h3>
        {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ author.get_full_name }}
              <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>
          {{ post.text }}
          </p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
        </article>
        {% if post.group %}
        Группа: {{ group.title }}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}